version: '3.9'

services:
  backend-email:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - 8000:8000
    volumes:
      - ./apps/email:/apps/email
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    # command: >
    #   sh -c "django-admin startproject ambassador"
